
export const createDashboardJson = () => {
  const data = `{
  "en": {
    "test": "In the beginning was the Word, and the Word was with God, and the Word was God. 2This was in the beginning with God. 3All things were made through him, and without him nothing was made that was made. 4In him was life, and life was the light of men. 5The light shines in the darkness, and the darkness did not prevail against it. 6There was a man sent from God, whose name was John. 7This man came as a testimony, to bear witness to the light, so that all might believe through him. 8He was not the light, but that he might bear witness to the light. 9That true light, which enlightens every man, came into this world. 10He was in the world, and the world was made by him; but the world did not know him. 11He came to his own, and his own did not receive him. 12But to all who received him, to those who believed in his name, he gave the right to become children of God; 13who were born not of blood, nor of the will of the flesh, nor of the will of man, but of God. 14And that Word became flesh, and he dwelt among us (and we saw his glory, glory of him as of the only begotten of the Father), full of grace and truth. 15John bore witness of him, and cried out, saying, This is he of whom I said, He that cometh after me is before me; because he was first than me. 16For we all take from the fullness of him, and grace upon grace. 17For the law was given through Moses, but grace and truth came through Jesus Christ. 18No one has ever seen God; the only begotten Son, who is in the bosom of the Father, he has made him known."
  },
  "por": {
    "test": "No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus. 2Isso aconteceu no princípio com Deus. 3Todas as coisas foram feitas por meio dele, e sem ele nada do que foi feito se fez. 4Nele estava a vida, e a vida era a luz dos homens. 5A luz brilha nas trevas, e as trevas não prevaleceram contra ela. 6Houve um homem enviado por Deus, cujo nome era João. 7Este homem veio como testemunho, para dar testemunho da luz, para que todos cressem por meio dele. 8Ele não era a luz, mas para que pudesse dar testemunho da luz. 9Essa verdadeira luz, que ilumina todo homem, veio a este mundo. 10Ele estava no mundo, e o mundo foi feito por ele; mas o mundo não o conheceu. 11Ele veio para o que era seu, e os seus não o receberam. 12Mas a todos os que o receberam, aos que creram no seu nome, ele deu o direito de se tornarem filhos de Deus; 13que não nasceram do sangue, nem da vontade da carne, nem da vontade do homem, mas de Deus. 14E aquele Verbo se fez carne e habitou entre nós (e vimos a sua glória, glória como do unigênito do Pai), cheio de graça e de verdade. 15João deu testemunho dele e clamou, dizendo: Este é aquele de quem eu disse: O que vem depois de mim está diante de mim; porque ele foi primeiro que eu. 16Pois todos nós recebemos da sua plenitude, e graça sobre graça. 17Porque a lei foi dada por meio de Moisés, mas a graça e a verdade vieram por meio de Jesus Cristo. 18Ninguém jamais viu a Deus; o Filho unigênito, que está no seio do Pai, ele o deu a conhecer."
  },
  "fre": {
    "test": "Au commencement était la Parole, et la Parole était avec Dieu, et la Parole était Dieu. 2C’était au commencement avec Dieu. 3Toutes choses ont été faites par lui, et rien de ce qui a été fait n'a été fait sans lui. 4En lui était la vie, et la vie était la lumière des hommes. 5La lumière brille dans les ténèbres, et les ténèbres n’ont pas prévalu contre elle. 6Il y avait un homme envoyé de Dieu, nommé Jean. 7Cet homme est venu en témoignage, pour rendre témoignage à la lumière, afin que tous croient par lui. 8Il n'était pas la lumière, mais pour rendre témoignage à la lumière. 9Cette vraie lumière, qui éclaire tout homme, est venue dans ce monde. 10Il était dans le monde, et le monde a été fait par lui ; mais le monde ne le connaissait pas. 11Il est venu chez lui, et les siens ne l'ont pas reçu. 12Mais à tous ceux qui l'ont reçu, à ceux qui ont cru en son nom, il a donné le droit de devenir enfants de Dieu ; 13qui sont nés non du sang, ni de la volonté de la chair, ni de la volonté de l'homme, mais de Dieu. 14Et cette Parole s'est faite chair et a habité parmi nous (et nous avons vu sa gloire, gloire comme celle du Fils unique du Père), pleine de grâce et de vérité. 15Jean en rendit témoignage et s'écria, disant : C'est celui dont j'ai dit : Celui qui vient après moi est devant moi ; parce qu'il était le premier que moi. 16Car nous prenons tous de sa plénitude, et grâce sur grâce. 17Car la loi a été donnée par Moïse, mais la grâce et la vérité sont venues par Jésus-Christ. 18Personne n’a jamais vu Dieu ; le Fils unique, qui est dans le sein du Père, il l'a fait connaître."
  },
  "es": {
    "test": "En el principio era el Verbo, y el Verbo era con Dios, y el Verbo era Dios. 2Este era en el principio con Dios. 3Todas las cosas por él fueron hechas, y sin él nada de lo que ha sido hecho, fue hecho. 4En él estaba la vida, y la vida era la luz de los hombres. 5La luz en las tinieblas resplandece, y las tinieblas no prevalecieron contra ella. 6Hubo un hombre enviado de Dios, el cual se llamaba Juan. 7Este vino por testimonio, para que diese testimonio de la luz, a fin de que todos creyesen por él. 8No era él la luz, sino para que diese testimonio de la luz. 9Aquella luz verdadera, que alumbra a todo hombre, venía a este mundo. 10En el mundo estaba, y el mundo por él fue hecho; pero el mundo no le conoció. 11A lo suyo vino, y los suyos no le recibieron. 12Mas a todos los que le recibieron, a los que creen en su nombre, les dio potestad de ser hechos hijos de Dios; 13los cuales no son engendrados de sangre, ni de voluntad de carne, ni de voluntad de varón, sino de Dios. 14Y aquel Verbo fue hecho carne, y habitó entre nosotros (y vimos su gloria, gloria como del unigénito del Padre), lleno de gracia y de verdad. 15Juan dio testimonio de él, y clamó diciendo: Este es de quien yo decía: El que viene después de mí, es antes de mí; porque era primero que yo. 16Porque de su plenitud tomamos todos, y gracia sobre gracia. 17Pues la ley por medio de Moisés fue dada, pero la gracia y la verdad vinieron por medio de Jesucristo. 18A Dios nadie le vio jamás; el unigénito Hijo, que está en el seno del Padre, él le ha dado a conocer."
  }
}
`;
  return data;
}
